### ISSUE TITLE
User profiles inherited multiple times when :user is a composite profile

### ISSUE THREAD

**Issue by hugoduncan** [jcrossley3/lein-modules#25]
When the `:user` profile is composite, the user profiles specified by `:user` are inherited multiple times, which can lead to incorrect values for merged vectors in the profile.

**Comment by jcrossley3** [comment]
Noting a comment from @hugoduncan on irc: "lein-modules breaks profile merging when the :user profile is a composite (as it then doesn't get filtered in lein-modules.inheritance/filter-profiles)"

**Comment by jcrossley3** [comment]
@hugoduncan I'm having a hard time reproducing this. I don't think a composite :user profile would prevent it from being excluded by filter-profiles. can you provide a simple example?
