### ISSUE TITLE
Profile composition order

### ISSUE THREAD

**Issue by modax** [jcrossley3/lein-modules#26]
Hello,

given the following directory structure:

    $ cat ./project.clj
<pre>
(defproject proj/parent "1"
  :plugins [[lein-modules "0.3.10"]]
  :profiles
  {:dev [{ :pstuff ["p"]} ]})
</pre>

    $ cat ./child1/project.clj
<pre>
(defproject proj/child1 "1"
  :plugins [[lein-modules "0.3.10"]]
  :profiles {:dev [ { :c1stuff ["c1"] } ]})
</pre>

    $ cat ./child1/child2/project.clj
<pre>
(defproject proj/child2 "1"
  :plugins [[lein-modules "0.3.10"]]
  :profiles {:dev [ { :c2stuff ["c2"] } ]})
</pre>

when I run the following, I get:

<pre>
$ lein modules show-profiles dev
 Module build order:
   child1
   child2
------------------------------------------------------------------------
 Building child1 1 (base,system,user,provided,dev)
------------------------------------------------------------------------
[{:c1stuff ["c1"]} {:pstuff ["p"]}]
------------------------------------------------------------------------
 Building child2 1 (base,system,user,provided,dev)
------------------------------------------------------------------------
[{:c2stuff ["c2"]} {:c1stuff ["c1"]} {:pstuff ["p"]}]
</pre>

Why is parent profile applied *after* child profile? Shouldn't child profiles be preferred over (i.e. given a chance to override) parent profiles?

**Comment by jcrossley3** [comment]
I'm not sure I see the problem here. The most immediate ancestors take precedence, so the order appears correct to me: [c2, c1, p]. What was your expectation?

**Comment by jcrossley3** [comment]
@mdxinventi Can I close this or am I misunderstanding a real problem? Thanks!
