### ISSUE TITLE
Overriding base profiles in child projects

### ISSUE THREAD

**Issue by dm3** [jcrossley3/lein-modules#27]
Leiningen includes tools.nrepl as a dependency on the `:base` profile. In order for a project to be able to depend on `tools.nrepl` in compile scope, one can override the dependencies of the `:base` profile via:

```
  :profiles {:base {:dependencies ^:replace []}})
```

However, applying the above to a child profile will not work. The project map created when performing `lein` actions on the child profile will contain the `[:base-parent :base-child]` where only the `:base-child` has the override applied to it.

Would be nice to have a way to achieve the above goal without having to apply the same override across the inheritance chain.

**Comment by jcrossley3** [comment]
There seem to be a number of open issues around this, e.g. https://github.com/technomancy/leiningen/issues/1771
