### ISSUE TITLE
Dummy Jar installation?

### ISSUE THREAD

**Issue by icambron** [jcrossley3/lein-modules#28]
One thing that's a bit annoying with modules (and really Lein in general) is that you have to install the jar before checkouts will work. Maybe there are good reasons this isn't a good idea, but would it make sense for `lein modules :checkouts` to install dummy, empty jars if they're not there? Then checkouts will work without the need to run `lein modules install`.

**Comment by jcrossley3** [comment]
I agree it's annoying and often a point of confusion. I suppose we could just run the `install` task for each module when the :checkouts option is passed. Would that work for you?

**Comment by icambron** [comment]
I tried that, with just a shell script, but it turned out to be sort of unfortunate for my case. In my environment, I have to run `:checkouts` a *lot* because...well, it's complicated and boring. But `install` takes forever and I really only need it the first time, so I only want to run it if it's necessary; i.e. when the jars aren't there. So for me personally, I'd rather have the explicit, unexpected step upfront that eat the cost every time. But probably most people only run `:checkouts` once, so it's all the same to them.

The other reason it's not ideal is that `install` means things actually need to compile, which is why I was suggesting a dummy jar. But that second part isn't such a big deal.

**Comment by jcrossley3** [comment]
This is annoying, but it's "The Maven Way" so I'm closing until someone comes up with a better idea.
