### ISSUE TITLE
lein-modules no longer works with Leiningen 2.7.1

### ISSUE THREAD

**Issue by d4span** [jcrossley3/lein-modules#35]
Leiningen 2.7.1 breaks lein-modules. For instance, running `lein modules install` on a parent project results in a failed build with output of the form:

`> lein modules install`
`Error loading /path/to/moduleA/project.clj`
...
`Error loading /path/to/moduleZ/project.clj`
`No modules found`

Everything works fine with Leiningen 2.7.0 and previous versions of Leiningen.

**Comment by jcrossley3** [comment]
Thanks for the report. I can reproduce the error. I'll try to look at it this week.

**Comment by jcrossley3** [comment]
This is a duplicate of https://github.com/technomancy/leiningen/issues/2212 which has been fixed in master. I've verified that all lein-modules tests pass using a locally-built vesion of lein that includes this fix, so all should be well once 2.7.2 is released. Thanks!
